---
title: "Jan262024"
output: html_document
date: "2024-01-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
# Creat a vector of names for independent variables.  Call the vector #IV
```{r}
IV<-c("A","B", "C","D", "E", "F", "G", "H", "I", "J")
```

#Create a list containing slopes for each combination of the ten independent variables

```{r}

Slopes <- list(
  D1 = c(10, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  D2 = c(5, 5, 0, 0, 0, 0, 0, 0, 0, 0),
  D3 = c(3.333, 3.333, 3.333, 0, 0, 0, 0, 0, 0, 0),
  D4 = c(2.5, 2.5, 2.5, 2.5, 0, 0, 0, 0, 0, 0),
  D5 = c(2, 2, 2, 2, 2, 0, 0, 0, 0, 0),
  D6 = c(1.666, 1.666, 1.666, 1.666, 1.666, 1.666, 0, 0, 0, 0),
  D7 = c(1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 1.48, 0, 0, 0),
  D8 = c(1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 0, 0),
  D9 = c(1.111, 1.111, 1.111, 1.111, 1.111, 1.111, 1.111, 1.111, 1.111, 0),
  D10 = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1))


```

# Set row counter to 0

```{r}
row_counter <- 0
Intercept<-0
```


#Set up all of the for loops to cycle through differnt number of drivers a
# different number of samples, different number of samples, differnt amounts #of meaurement error

```{r}
# Initialize an empty data frame
data <- data.frame()

for (i in 1:1) {  
  for (j in 1:1) {  
    if (i == 1) {  
      for (k in 1:1) {
        for (n_values in c(5)) {
          for (sd1 in c(50)) {
            for (sd2 in c(50)) {
              for (sd3 in c(50)) {
                for (n_reps in 1:1) {
                  variable_list <- list()  

                  for (drivers in IV) {
                    variable_values <- rnorm(n_values, mean = 0, sd = sd1)
                    variable_list[[drivers]] <- variable_values
                  }
                  IV_k <- IV[k]  # Store IV[k] in a variable
                  SR <- Intercept + Slopes[[i]][k] * variable_list[[IV_k]]  + rnorm(n_values, 0, sd2)
                  
                  # Create a data frame for the current iteration and append it to the existing data
                  current_data <- setNames(data.frame(SR, variable_list[[IV_k]]), c("SR", IV_k))
                  data <- rbind(data, current_data)
                }
              }
            }
          }
        }
      }
    } else {  
      for (k in 1:2) {
        for (n_values in c(5)) {
          for (sd1 in c(50)) {
            for (sd2 in c(50)) {
              for (sd3 in c(50)) {
                for (n_reps in 1:1) {
                  variable_list <- list()  

                  for (drivers in IV) {
                    variable_values <- rnorm(n_values, mean = 0, sd = sd1)
                    variable_list[[drivers]] <- variable_values
                  }
                  IV_k <- IV[k]  # Store IV[k] in a variable
                  SR1 <- Intercept + Slopes[[i]][k] * variable_list[[IV_k]]  + rnorm(n_values, 0, sd2)
                  
                  # Create a data frame for the current iteration and append it to the existing data
                  current_data <- setNames(data.frame(SR1, variable_list[[IV_k]]), c("SR", IV_k))
                  data <- rbind(data, current_data)
                }
              }
            }
          }
        }
      }
    }
  }
}

         
```

